export const actionTypes = {
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",

  PRODUCT_DETAIL_REQUEST: "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS: "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_FAIL: "PRODUCT_DETAIL_FAIL",

  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_SAVE_SHIPPING_ADDRESS: "CART_SAVE_SHIPPING_ADDRESS",
  CART_SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_lOGOUT",

  USER_SIGNOUT_REQUEST: "USER_SIGNOUT_REQUEST",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAIL: "USER_SIGNOUT_FAIL",

  USER_DETAIL_REQUEST: "USER_DETAIL_REQUEST",
  USER_DETAIL_SUCCESS: "USER_DETAIL_SUCCESS",
  USER_DETAIL_FAIL: "USER_DETAIL_FAIL",
  USER_DETAIL_RESET: "USER_DETAIL_RESET",

  USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  USER_UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",

  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",

  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",
  ORDER_DETAILS_RESET: "ORDER_DETAILS_RESET",

  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  ORDER_LIST_MY_REQUEST: "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS: "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_FAIL: "ORDER_LIST_MY_FAIL",
  ORDER_LIST_MY_RESET: "ORDER_LIST_MY_RESET",
};
